site_name: Ordeez Help Center
theme:
  name: material

nav:
  - Getting Started:
      - Set Up Your Store: getting-started/setup-store.md
      - Create a Product: getting-started/create-product.md
  